[window]
#opacity = 0.4
opacity = 1.0

[font]
normal = { family = "SauceCodePro NF", style = "Medium" }
bold = { family = "SauceCodePro NF", style = "Bold" }
italic = { family = "SauceCodePro NF", style = "Italic" }
bold_italic = { family = "SauceCodePro NF", style = "BoldItalic" }

#[colors.primary]
#background = "#14161b"
#background = "#040817"
#background = "#12101d"


