[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = false

[colors.bright]
black = "#555753"
blue = "#739fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.cursor]
cursor = "#ffffff"

[colors.normal]
black = "#000000"
blue = "#3465a4"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#75507b"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#c4a000"

[colors.primary]
background = "#0F0F0F"
foreground = "#ffffff"

[cursor]
thickness = 0.1
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12.0

[font.normal]
family = "Source Code Pro"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 1
y = 0
